Experiment_name: ST-TR

# feeder
feeder: feeders.feeder.Feeder
num_workers: 8
train_feeder_args:
  data_path: /data1/dataset/ntu/xsub/train_data_joint.npy
  label_path: /data1/dataset/ntu/xsub/train_label.pkl
  # debug: True
  random_choose: False
  random_shift: True
  random_move: True
  window_size: -1
  normalization: True

test_feeder_args:
  data_path: /data1/dataset/ntu/xsub/val_data_joint.npy
  label_path: /data1/dataset/ntu/xsub/val_label.pkl
  # debug: True
  random_choose: False
  random_shift: False
  random_move: False
  window_size: -1
  normalization: True

# model_config_method: 1

# model
model: ST_TR.TR_model.Model
model_args:
  num_heads: 8
  hidden_size: 128
  ff_size: 256
  num_layers: 1
  dropout: 0.3
  emb_dropout: 0.3
  s_local_num_layers: 0
  t_local_num_layers: 1
  drop_path_rate: 0.1
  window_size: 25
  max_relative_positions: 300

  input_channel: 3
  block_num: 6
  point_num: 25
  class_num: 60

  end_t_num_layer: 6


# weights: 

#optim
optim: Adam
weight_decay: 0.0001
lr: 0.0001
step: [60, 80, 100]

# training
phase: train
# debug: False
device: [0, 1, 2, 3]
only_train_epoch: 1
warm_up_epoch: 10
batch_size: 4
epochs: 140
nesterov: True