Experiment_name: BDCI
## dropout and weight_decay

# feeder
feeder: feeders.feeder_BDCI.Feeder
num_workers: 8
train_feeder_args:
# test_feeder_args:
  data_path: /home/zqp/code/BDCI/processed_data/train_data.npy
  label_path: /home/zqp/code/BDCI/processed_data/train_label.npy
  # debug: True
  random_choose: False
  random_shift: True
  random_move: True
  window_size: 64
  normalization: True
  use_gauss: False

# train_feeder_args:
test_feeder_args:
  data_path: /home/zqp/code/BDCI/processed_data/eval_data.npy
  label_path: /home/zqp/code/BDCI/processed_data/eval_label.npy
  # debug: True
  random_choose: False
  random_shift: False
  random_move: False
  window_size: -1
  normalization: True
  use_gauss: False

# model
# model: ST_TR.model_GCN_Str.Model
model: model.model_others.Model
model_args:
  graph: 'graph.ntu_rgb_d.Graph'
  kernel_num: 8
  edge_weight: True
  lamda: 1
  in_channels: 2
  n_class: 30

# weights: work_dir/MuiltKernelGTCN2021-08-23/save_models/MuiltKernelGTCN-100.pt


#optim
optim: Adam
weight_decay: 0.0001
lr: 0.005
step: [35, 80, 100]

# training
phase: train
debug: False
device: [0, 1, 2, 3]
only_train_epoch: 1
warm_up_epoch: 5
batch_size: 8
epochs: 140
nesterov: True

log_interval: 10