Experiment_name: TCLS_SCLS_gauss

# feeder
feeder: feeders.feeder.Feeder
num_workers: 8
train_feeder_args:
  data_path: /home1/zqp_workspace/Shift-GCN/data/ntu/xsub/train_data_joint.npy
  label_path: /home1/zqp_workspace/Shift-GCN/data/ntu/xsub/train_label.pkl
  # debug: True
  random_choose: False
  random_shift: True
  random_move: True
  window_size: -1
  normalization: True
  use_gauss: True
  gauss_mu: 0
  gauss_sigma: 0.05

test_feeder_args:
  data_path: /home1/zqp_workspace/Shift-GCN/data/ntu/xsub/val_data_joint.npy
  label_path: /home1/zqp_workspace/Shift-GCN/data/ntu/xsub/val_label.pkl
  # debug: True
  random_choose: False
  random_shift: False
  random_move: False
  window_size: -1
  normalization: True
  use_gauss: False
  gauss_mu: 0
  gauss_sigma: 0.01

# model
model: model.TR_GCN_model_local_one_more_S.Model
model_args:
  graph: graph.ntu_rgb_d.Graph
  kernel_num: 8
  edge_weight: True
  lamda: 1
  input_channel: 3
  mid_channels: [64, 64]
  layer_num: 3
  heads: 8 
  encode_size: 64 
  d_ff: 128
  dropout: 0.3 
  position_encoding_dropout: 0.3
  point_num: 25 
  n_classes: 60

weights: work_dir/TCLS_SCLS_gauss2021-04-07/save_models/TCLS_SCLS_gauss-40.pt


#optim
optim: Adam
weight_decay: 0.0001
lr: 0.001
step: [30, 80, 100]

# training
phase: train
debug: False
device: [0, 1]
only_train_epoch: 1
warm_up_epoch: 10
batch_size: 32
epochs: 140
nesterov: True
