Experiment_name: xsub_joint
## dropout and weight_decay

# feeder
feeder: feeders.feeder_new.Feeder
num_workers: 8
train_feeder_args:
# test_feeder_args:
  data_path: /home/zqp/dataset/ntu/ntu_new/xsub/train_data_joint.npy
  label_path: /home/zqp/dataset/ntu/ntu_new/xsub/train_label.pkl
  len_path: /home/zqp/dataset/ntu/ntu_new/xsub/train_len.npy
  # debug: True
  random_choose: False
  random_shift: False
  random_move: False
  window_size: 96
  normalization: False
  use_gauss: True

# train_feeder_args:
test_feeder_args:
  data_path: /home/zqp/dataset/ntu/ntu_new/xsub/val_data_joint.npy
  label_path: /home/zqp/dataset/ntu/ntu_new/xsub/val_label.pkl
  len_path: /home/zqp/dataset/ntu/ntu_new/xsub/val_len.npy
  # debug: True
  random_choose: False
  random_shift: False
  random_move: False
  window_size: 96
  normalization: False
  use_gauss: False

# model
model: ST_TR.model_GCN_Str.Model
model_args:
  graph: 'graph.ntu_rgb_d.Graph'
  kernel_num: 8
  edge_weight: True
  lamda: 1
  in_channels: 3
  n_class: 60

# weights: work_dir/MuiltKernelGTCN_Str_drop_add2021-10-14/save_models/MuiltKernelGTCN_Str_drop_add-51.pt

#optim
optim: SGD
weight_decay: 0.0001
lr: 0.1
step: [35, 80, 100]

# training
phase: train
debug: False
device: [0, 1] 
only_train_epoch: 0
warm_up_epoch: 5
batch_size: 64
epochs: 140
nesterov: True

log_interval: 10
