Experiment_name: MuiltKernelGTCN_Str_similar_adam
## dropout and weight_decay

# feeder
feeder: feeders.feeder.Feeder
num_workers: 8
train_feeder_args:
  data_path: /data1/dataset/ntu_short_split/xsub/train_data_joint.npy
  label_path: /data1/dataset/ntu_short_split/xsub/train_label.pkl
  # debug: True
  random_choose: False
  random_shift: True
  random_move: True
  window_size: -1
  normalization: True

test_feeder_args:
  data_path: /data1/dataset/ntu_short_split/xsub/val_data_joint.npy
  label_path: /data1/dataset/ntu_short_split/xsub/val_label.pkl
  # debug: True
  random_choose: False
  random_shift: False
  random_move: False
  window_size: -1
  normalization: True
  use_gauss: False

# model
model: ST_TR.model_GCN_Str.Model
model_args:
  graph: 'graph.ntu_rgb_d.Graph'
  kernel_num: 8
  edge_weight: True
  lamda: 1
  in_channels: 3
  n_class: 60

# weights: work_dir/MuiltKernelGTCN_Str_con_52021-09-14/save_models/MuiltKernelGTCN_Str_con_5-125.pt

#optim
optim: Adam
weight_decay: 0.00001
lr: 0.001
step: [35, 80, 100]

# training
phase: train
debug: False
device: [0, 1, 2, 3]
only_train_epoch: 1
warm_up_epoch: 5
batch_size: 192
epochs: 140
nesterov: True