Experiment_name: TCLS_SCLS_pos_aware_56class

# feeder
feeder: feeders.feeder.Feeder
num_workers: 8
train_feeder_args:
  data_path: ./data/ntu/xsub/train_data_joint_56.npy
  label_path: ./data/ntu/xsub/train_label_56.pkl
  # debug: True
  random_choose: False
  random_shift: True
  random_move: True
  window_size: -1
  normalization: True
  use_gauss: True
  gauss_mu: 0
  gauss_sigma: 0.05

test_feeder_args:
  data_path: ./data/ntu/xsub/val_data_joint_56.npy
  label_path: ./data/ntu/xsub/val_label_56.pkl
  debug: False
  random_choose: False
  random_shift: False
  random_move: False
  window_size: -1
  normalization: True
  use_gauss: False
  gauss_mu: 0
  gauss_sigma: 0.01

# model
model: pos_aware.pos_GCN_model.Model
model_args:
  graph: graph.ntu_rgb_d.Graph
  kernel_num: 8
  edge_weight: True
  lamda: 1
  input_channel: 3
  mid_channels: [32, 64]
  layer_num: 3
  heads: 8 
  encode_size: 64 
  d_ff: 128
  dropout: 0.3 
  position_encoding_dropout: 0.3
  point_num: 25 
  n_classes: 56

# weights: work_dir/TCLS_SCLS_pos_aware2021-04-09/save_models/TCLS_SCLS_pos_aware-50.pt


#optim
optim: Adam
weight_decay: 0.0001
lr: 0.001
step: [30, 80, 100]

# training
phase: train
debug: False
device: [0, 1]
only_train_epoch: 1
warm_up_epoch: 10
batch_size: 48
epochs: 140
nesterov: True

log_interval: 100
